CharactersTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:custom.CharactersTable.name}
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: externalId
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: externalIdIndex
        KeySchema:
          - AttributeName: externalId
            KeyType: HASH
        Projection:
          ProjectionType: ALL
    BillingMode: PAY_PER_REQUEST